name: e_commerce_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

#----------------Packages----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.6.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^2.0.1
  flutter_rating_bar: ^4.0.1

  # Some usefull packages
  carousel_slider: ^5.1.1

#----------------End Packages----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #-----------------My Assets-----------------#
  assets:
    - assets/images/
    - assets/icons/social_media/
    - assets/icons/categories/
    - assets/images/on_boarding_images/
    - assets/images/pictures/
    - assets/images/products/
    - assets/images/user/
    - assets/images/banners/
    - assets/logos/

  #-----------------My Fonts-----------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
  #-----------------End Assets-----------------#
